[package]
name        = "flix"       # The name of the package.
description = "system"     # The description of the package.
version     = "0.35.0"     # The semantic version of the package.
flix        = "0.35.0"     # The required version of the Flix compiler.
libLevel   = "nix"
src        = "src"
license     = "Apache-2.0" # The license applicable to this project (see also LICENSE.md).
authors     = []           # The authors of this project.
